RETO 1. 

CREACIÓN TABLA LOCALIDADES

CREATE TABLE localidades (
    id_localidad INTEGER PRIMARY KEY,
    ciudad VARCHAR2 (50) NOT NULL,
    provincia VARCHAR2 (50) NOT NULL,
    codigo_postal VARCHAR2 (10) NOT NULL
);

Comentarios:

TABLA LOCALIDADES recoge la ciudad, la provincia y el código postal,  
comunicado con la tabla estudiante a través de una clave primaria id_localidad
que sirve de clave foránea en la tabla estudiante. Así limpiamos la tabla estudiantes, 
evitamos la redundancia y le damos coherencia. Utilizamos restricciones adicionales NOT NULL para obligar a rellenar los campos.

CREACIÓN TABLA ESTUDIANTE

CREATE TABLE estudiante (
    codigo_estudiante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nombre VARCHAR2 (100) NOT NULL,
    apellidos VARCHAR2 (100) NOT NULL, 
    direccion VARCHAR2 (100) NOT NULL,
    telefono VARCHAR2 (15) NOT NULL UNIQUE,
    fecha_nacimiento DATE NOT NULL,
    id_localidad INTEGER NOT NULL,
    FOREIGN KEY (id_localidad) REFERENCES localidades (id_localidad)
);

Comentarios: 

1. Utilizamos un integer porque en ORACLE es sinónimo de un NUMBER con precisión 38.
2. Hacemos uso de la función GENERATED BY DEFAULT AS IDENTITY para que rellene número 
a número de forma automática y le damos al atributo la clave primaria PRIMARY KEY, 
que servirá para relacionarlo con la tabla estancias.
3. Nombre, apellidos, dirección, lo ponemos como tipo texto VARCHAR2 al que damos una longitud estándar de 100 bastante holgada.
4. Marcamos un valor diferencia importante, ya que he usado VARCHAR2 en codigo_postal y 
telefono porque aunque parezcan números, no vamos a hacer operaciones matemáticas con ellos. 
Es más, el código postal puede empezar por cero (por ejemplo, 08001) y si fuera NUMERIC u 
INTEGER, el cero inicial se perdería. Además, el teléfono puede contener ceros al principio o 
incluso signos (+34), y también podría ser más largo que el límite de un entero.
Por eso es más seguro y correcto almacenarlos como cadena de caracteres usando VARCHAR2. 
5. A la fecha le daremos el formato esperado DATE.
6. Como podemos ver, hemos utilizado restricciones adicionales NOT NULL en todos los 
atributos que no son clave primaria para que no se puedan dejar vacíos, y también 
UNIQUE en telefono para que cada estudiante tenga un teléfono único asociado y no
puedan repetirse aunque vivan juntos (vamos, obligo a que cada estudiante se 
compre un móvil, XD).
7. Creamos una clave foránea id_localidad que nos permitirá comunicar la tabla estudiante con la tabla localidades.

CREACIÓN TABLA TUTOR

CREATE TABLE tutor (
    codigo_tutor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nombre VARCHAR2 (100) NOT NULL,
    apellidos VARCHAR2 (100) NOT NULL,
    telefono VARCHAR2 (15) NOT NULL UNIQUE,
    especialidad VARCHAR2 (50) NOT NULL
);

Comentarios:

En este caso hemos utilizado los mismos recursos que en la tabla estudiante (GENERATED BY DEFAULT...PRIMARY KEY, VARCHAR2 y NOT NULL. Podríamos haber hecho lo mismo que con la tabla estudiante, haber generado una tabla especialidades, pero en este caso, debido a la sencillez del modelo me ha parecido suficiente y adecuado, ya que el enunciado no requiere una tabla de especialidades separada.

CREACIÓN TABLA ESTANCIAS

CREATE TABLE estancias (
    codigo_estancia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_habitacion INTEGER NOT NULL, 
    cama_asignada INTEGER NOT NULL,
    fecha_entrada DATE DEFAULT SYSDATE NOT NULL, 
    codigo_estudiante INTEGER NOT NULL,
    codigo_tutor INTEGER NOT NULL,
    FOREIGN KEY (codigo_estudiante) REFERENCES estudiante (codigo_estudiante),
    FOREIGN KEY (codigo_tutor) REFERENCES tutor (codigo_tutor)
);

Comentarios:

En este caso hacemos uso de los mismos recursos que en las dos tablas anteriores y, además utilizamos SYSDATE como DEFAULT, y dos claves foráneas que hacen referencia a las tablas estudiante y tutor, a través de los atributos código_estudiante y código_tutor respectivamente. Esto permite relacionar las tablas.

CREACIÓN VISTAS

CREACIÓN VISTA a)

CREATE OR REPLACE VIEW estudiante_tutor AS
SELECT esta.codigo_estudiante, estu.nombre, estu.apellidos, estu.direccion, estu.telefono,estu.fecha_nacimiento, l.ciudad, l.provincia, l.codigo_postal, t.nombre || ' ' || t.apellidos AS nombre_tutor
FROM estancias esta
JOIN estudiante estu ON esta.codigo_estudiante = estu.codigo_estudiante
JOIN tutor t ON esta.codigo_tutor = t.codigo_tutor
JOIN localidades l ON estu.id_localidad = l.id_localidad;

Comentarios: 

Hemos creado una vista que muestra toda la información de los estudiantes junto con el tutor que les atiende en cada estancia. Aquí usamos JOINs (llegando a unir 4 tablas) con claves primarias y foráneas que permiten unir las tablas. Como vemos, no se usa la palabra DISTINCT porque un estudiante puede tener varias estancias y un tutor puede ser asignado a varias estancias, por lo que en la vista se podrían ver repetidos los estudiantes si han tenido más de una estancia, y es lo que nos interesa (además de los tutores).

CREACIÓN VISTA b)

CREATE OR REPLACE VIEW numero_estancias_estudiante AS
SELECT est.codigo_estudiante, est.nombre, est.apellidos, COUNT(esta.codigo_estancia) AS numero_estancias
FROM estancias esta
JOIN estudiante est ON esta.codigo_estudiante = est.codigo_estudiante
GROUP BY est.codigo_estudiante, est.nombre, est.apellidos;

Comentarios:

Esta vista me ha parecido muy interesante de crear. Básicamente se establece un JOIN para unir la tabla estancias con la tabla estudiante. Lo importante aquí es entender que usamos COUNT(esta.codigo_estancia) como función de agregación, y que todas las columnas que no están dentro de una función de agregación (codigo_estudiante, nombre, apellidos) deben aparecer en el GROUP BY. Al principio no era consciente de esto y tuve dificultades hasta darme cuenta de ese detalle.

CREACIÓN VISTA c)

CREATE OR REPLACE VIEW numero_estudiantes_tutor AS
SELECT t.nombre || ' ' || t.apellidos AS nombre_tutor, COUNT(DISTINCT esta.codigo_estudiante) AS numero_estudiantes
FROM estancias esta
JOIN tutor t ON esta.codigo_tutor = t.codigo_tutor
GROUP BY t.nombre, t.apellidos;

Comentarios:

En este caso nos vemos en un ejemplo parecido al anterior, sin embargo, un factor fundamental es que hemos utilizado DISTINCT para diferenciar cuando más de una estancia tienen el mismo tutor y el mismo alumno, es decir, cuando un tutor tiene 2 estancias y justo coincide en ambas con el mismo estudiante.

COMANDOS DE VISUALIZACIÓN VISTAS CREADAS

A)

SELECT * 
FROM estudiante_tutor
ORDER BY codigo_estudiante ASC;

Llamamos a la vista y aprovechamos para decirle que nos la ordene teniendo en cuenta codigo_estudiante de forma ascendente, buscando que ponga (1, 2, 3,...).

B)

SELECT * 
FROM numero_estancias_estudiante
ORDER BY numero_estancias DESC;

Hacemos lo mismo que antes, pero esta vez buscamos un orden descendente a través de numero_estancias, para que aparezcan primero los resultados que mayor número de estancias tienen.

C)

SELECT *
FROM numero_estudiantes_tutor
ORDER BY numero_estudiantes DESC;

Aquí aplicamos la misma lógica que en la vista anterior, pero esta vez ordenamos en función de numero_estudiantes, para que aparezcan en primer lugar los tutores con mayor número de estudiantes asignados.

FIN;

